### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by scpedicini** [thdk/TS3-projects-references-example#2]
@thdk I can't get this sample to work at all, tsc will build all three projects with zero issues, but any attempts at actually running them using ts-node or node 16 result in:
`import { logProjectName } from '../common'; ^^^^^^ SyntaxError: Cannot use import statement outside a module`

Any ideas?

**Comment by thdk** [comment]
This project is written with ecmascript modules instead of commonjs modules.

Because it's created to run in browsers. 

Node used to work only with commonjs modules but by now it should also work for both es modules and commonjs modules.

For node you must enable the es modules. https://nodejs.org/api/packages.html#type

Please ask your question on stackoverflow and I'll continue to help you from there if there is still need for more info.
